apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-demo-app
  template:
    metadata:
      labels:
        app: java-demo-app
    spec:
      containers:
      - name: java-demo
        image: drdocker108/java-demo:<IMAGE_TAG>
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-demo-service
spec:
  selector:
    app: java-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
